### ISSUE TITLE
Functional Use in Existing Frameworks

### ISSUE THREAD

**Issue by yangtaufoo** [xotahal/react-native-motion#1]
How would you intend to support navigation frameworks like RNN or React Nav, etc.?

**Comment by nimerfarahty** [comment]
interested for RNN specially

**Comment by xotahal** [comment]
Not sure what RNN is. Anyway, I was thinking about navigations - and it is not easy for shared element :) We still can move it from starting position to destination position ... but it is up to you to:
- turn off default animations that are done by these frameworks
- show rest of element on destination page after the animation is done (or when you want to show them - we can't know this, thus we can't do it for you)
