### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ahmedu007** [xotahal/react-native-motion#11]
Hey, just wondering if there is a possibility to add an Icon animation that takes 2 icons and spins them around? Just like <IconToggle /> we can probably have something like icon transitioner or spinner that would change the drop down to up or a search to close, and others.

**Comment by xotahal** [comment]
Hey @ahmedu007 👋Sorry for this late message. Did you manage it somehow? Do you have any gif/video about the animation you want to do?

**Comment by ahmedu007** [comment]
Hey, I cant even remember why I asked for this now 😥 
But I think I wanted something to morph Icons into each other, like the transition that happens when you open the top toolbar to search. 

https://codesandbox.io/s/31lzml4nr1?from-embed

Maybe something like this, may not be as smooth, but for font awesome icons?

**Comment by xotahal** [comment]
Oh, man 🤔 Looks nice ... But I would use `Lottie` for that one ...
