### ISSUE TITLE
Shake — Perform animation only when the new value is truthy.

### ISSUE THREAD

**Issue by jnicholls** [xotahal/react-native-motion#19]
Shake is an ideal animation for presenting feedback to users when there is an error in a form submission. Because errors are binary (there is either an error, or there isn't), it would be best to be able to trigger the Shake animation based on this binary value: truthy = shake, falsy = do-not-shake. But because there are other use cases for shaking, such as any change in value, the current check of value change is also pertinent and simply redundant in the truthy/falsy case.

For the above use case, in today's implementation when an error is removed, that binary trigger changes from `true` to `false` which invokes an animation when one is not expected or desired. In order to avoid that, one is required to do bookkeeping and boilerplate to trigger a Shake only when an error is introduced by, e.g., keeping a state variable that keeps track of error counts only when a fresh error introduced, but not when an error is removed.

I propose the additional check of animating only when the provided value is truthy. This makes it very easy to trigger when the triggering logic is binary such as "is there an error on this field?" or "is there an error in this form?" And, it still allows for triggering when there is an arbitrary change of value.

The only behavior regression this patch introduces is no longer triggering a Shake when the value goes from a truthy value to a non-truthy value. In my opinion, this is completely acceptable and quite intuitive.

**Comment by xotahal** [comment]
Already had a discussion about this on twitter - https://twitter.com/xotahal/status/1057391369373642752

Anyway, you are right and I can still keep both use cases ... will be changed as you suggest ;)

Thank you 🙏
