### ISSUE TITLE
Dynamic size for ListItemNode

### ISSUE THREAD

**Issue by am9r** [xotahal/react-native-motion#22]
many thanks for the great library,

I got an Issue an I am not quite sure how to resolve it.

I would like that my List Page Items to have dynamic size and extend or shrink based on their content. Making them a flex object resolve this issue, however when I tap an item the transitions works, however the height of the item shrinks down to a few pixels.

**Comment by KamranKhankhail** [comment]
@am9r I am suffering from same problem, but your mentioned trick doesn't seems to work, could you please help me understand where exactly you provide this `flexDirection: 'row'` property
