### ISSUE TITLE
Lack of documentation.

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [xotahal/react-native-motion#24]
I want to display the text/view in the center of the screen and then animate it to the top of the screen. How to achieve this in this library?

**Comment by jdnichollsc** [comment]
Using Flexbox and reviewing the [code](https://github.com/xotahal/react-native-motion/blob/master/src/TranslateY.js), any pull request to improve the README is welcome 👍

**Comment by xotahal** [comment]
As @jdnichollsc says. Any PR to make the documentation better is more than welcome ...
