### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by appasaheb4** [xotahal/react-native-motion#27]
ref.measure is not a function

**Comment by shashipyadav** [comment]
ref.measure is not a function

**Comment by xotahal** [comment]
Sorry but I think I can't help you with this

**Comment by appasaheb4** [comment]
Ok bro any hint...

**Comment by xotahal** [comment]
So if I were `semantic analyzator` I would say that `ref` is something what doesn't have definition of `measure` ...

**Comment by VacuumDecay** [comment]
@xotahal I think this should be reopened. I'm getting `cannot read property 'measure' of null` at SharedElement.js, line 196 using RN v0.59.4. Seems ref is being passed as null from onDestinationLayout?

**Comment by obiwankenoobi** [comment]
same here. `ref.measure is not a function `

**Comment by pianoman730** [comment]
Same issue here.

**Comment by appasaheb4** [comment]
which issue bro?

**Comment by pianoman730** [comment]
Ref.measure is not a function, as is stated in the description.

**Comment by appasaheb4** [comment]
it's solve i will put anwer

**Comment by pianoman730** [comment]
Oh awesome. Thanks!

**Comment by pianoman730** [comment]
@appasaheb4 Do you have a solution?

**Comment by appasaheb4** [comment]
yes bro i will put answer

**Comment by pianoman730** [comment]
@appasaheb4 When will you put an answer?

**Comment by pianoman730** [comment]
@appasaheb4 I'm not sure what you mean by `i will put answer`? Do you have something you can share with the rest of us about this issue?

**Comment by jdnichollsc** [comment]
Aren using a View component?

**Comment by anduscheung** [comment]
The content in `SharedElement` , both destination and source, must be wrapped with a `View`

**Comment by DavitVosk** [comment]
Can anyone please explain how to use this awesome package? Any example? I wrapped my `<App/>` with `SharedElementRenderer`,  I copy-pasted the same code on `DetailPage` screen from this package description and also wrapped my list item with `SharedElement`. But no success... :(
