### ISSUE TITLE
Upgrade to RN 0.60+

### ISSUE THREAD

**Issue by OlegPanfyorov** [xotahal/react-native-motion#34]
Hi there! Are you planning to upgrade your library to support RN 0.60 and remove all warnings like componentWillReceiveProps should be replaced?

**Comment by xotahal** [comment]
We should do that, yeah!

**Comment by OlegPanfyorov** [comment]
@xotahal I've created the PR, please review
https://github.com/xotahal/react-native-motion/pull/35
