### ISSUE TITLE
Duration not applied to show

### ISSUE THREAD

**Issue by ZeeStorm** [xotahal/react-native-motion#5]
https://github.com/xotahal/react-native-motion/blob/d65ed1dde25a338a1151cfa22ded719c56637c13/src/TranslateYAndOpacity.js#L54

I'm pretty certain `duration` should be passed here to the "show" function, and not just on the "hide" function.

**Comment by xotahal** [comment]
That's true ...

**Comment by jdnichollsc** [comment]
@ZeeStorm @xotahal this issue is fixed in this pull request :) https://github.com/xotahal/react-native-motion/pull/16/files
