### ISSUE TITLE
Example 

### ISSUE THREAD

**Issue by lucascoria** [xotahal/react-native-motion#7]
Is there an example of how to use this.

**Comment by NikiLee2016** [comment]
+1

**Comment by abhishkekalia** [comment]
+1

**Comment by williamgurzoni** [comment]
Hey, I really appreciate this component, but I need too a example. Is it possible to use with react navigation?

**Comment by mtzfactory** [comment]
+1

**Comment by Mont4** [comment]
+1

**Comment by xotahal** [comment]
### Playground for **react-native-motion** library

- [react-native-motion-playground](https://github.com/xotahal/react-native-motion-playground) repository
- [expo app](https://expo.io/@xotahal/react-native-motion-example)
- [Publication](https://medium.com/react-native-motion) about animation in React Native 🚗

**Comment by ali-sardari** [comment]
> ### Playground for **react-native-motion** library
> * [react-native-motion-playground](https://github.com/xotahal/react-native-motion-playground) repository
> * [expo app](https://expo.io/@xotahal/react-native-motion-example)
> * [Publication](https://medium.com/react-native-motion) about animation in React Native 🚗

this examples did not help me at all
